services:
  - type: web
    name: ej-hope-foundation
    runtime: node
    repo: https://github.com/iVGeek/EJFoundation
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: PUBLIC_PAYSTACK_KEY
        sync: false
      - key: PUBLIC_PAYSTACK_DEFAULT_CURRENCY
        value: KES